const jj = {
  kind: "youtube#captionListResponse",
  etag: "dUANUdARhsBxQz_lF4G_AwMReHk",
  items: [
    {
      kind: "youtube#caption",
      etag: "Ta_kAAfmtxOzgOwFQUVsRbuNH5o",
      id: "AUieDaZSw2JFTNutFi-HKpBeJ6w2ssdxHangesmz6CkW8X891jw",
      snippet: {
        videoId: "hgYhws0AHcg",
        lastUpdated: "2024-12-03T05:09:04.425846Z",
        trackKind: "asr",
        language: "en",
        name: "",
        audioTrackType: "unknown",
        isCC: false,
        isLarge: false,
        isEasyReader: false,
        isDraft: false,
        isAutoSynced: false,
        status: "serving",
      },
    },
    {
      kind: "youtube#caption",
      etag: "d8LyQvjLZWzw6SfsLp-Q7sQbyAs",
      id: "AUieDaZlqg-Ovhg1E4ejWQ3iDcIs4N7kISwHQPfBL8RUY26fHQ",
      snippet: {
        videoId: "hgYhws0AHcg",
        lastUpdated: "2024-12-02T07:51:27.914624Z",
        trackKind: "standard",
        language: "en",
        name: "en",
        audioTrackType: "unknown",
        isCC: false,
        isLarge: false,
        isEasyReader: false,
        isDraft: false,
        isAutoSynced: false,
        status: "serving",
      },
    },
  ],
};
